name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLproject/train_pca.csv"
  TARGET_VAR: "Credit_Score"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # Cek env
      - name: Check Env
        run: |
          echo "CSV_URL: $CSV_URL"
          echo "TARGET_VAR: $TARGET_VAR"

      # Install MLflow
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      # Jalankan MLflow Project
      - name: Run MLflow project
        run: |
          mlflow run . --env-manager=local

      # Ambil RUN_ID terakhir
      - name: Get latest MLflow run_id
        id: get_run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest RUN_ID: $RUN_ID"

      # Debug: list model folder
      - name: List model path
        run: |
          echo "Checking model path: mlruns/0/${RUN_ID}/artifacts/model"
          ls -R mlruns/0/${RUN_ID}/artifacts/model || echo "Model path not found"

      # Build Docker dari model
      - name: Build Docker Model
        run: |
          echo "Using RUN_ID: $RUN_ID"
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name cc

      # Cek Docker image
      - name: Debug docker image
        run: docker images | grep cc || echo "Docker image 'cc' not found"

      # Login ke Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Tag Docker image
      - name: Tag Docker Image
        run: |
          docker tag cc ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest

      # Push Docker image ke Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest
