name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLproject/train_pca.csv"
  TARGET_VAR: "Credit_Score"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: |
          echo "CSV_URL: $CSV_URL"
          echo "TARGET_VAR: $TARGET_VAR"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      - name: Run MLflow project
        run: |
          mlflow run MLproject --env-manager=local

      - name: Get latest MLflow run_id
        id: get_run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest RUN_ID: $RUN_ID"

      - name: List model path
        run: |
          echo "Checking model path: mlruns/0/${RUN_ID}/artifacts/model"
          if [ -d "mlruns/0/${RUN_ID}/artifacts/model" ]; then
            ls -R mlruns/0/${RUN_ID}/artifacts/model
          else
            echo "Model not found"; exit 1
          fi

      - name: Build Docker Model
        run: |
          echo "Using RUN_ID: $RUN_ID"
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name cc

      - name: Debug docker image
        run: docker images | grep cc || echo "Docker image 'cc' not found"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker Image
        run: |
          if docker images | grep -q cc; then
            docker tag cc ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest
          else
            echo "Image cc not found, tagging skipped"; exit 1
          fi

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest
